FROM node:8

# Install dependencies first to take advantage of caching

# Server package
WORKDIR /usr/src/app
COPY server/package*.json ./
RUN npm ci --only=production

# Copy rest of server and built client code
WORKDIR /usr/src/app
COPY server/ .
COPY client/build client-build

EXPOSE 5000
CMD [ "npm", "start" ]
