FROM node:8

# Install dependencies first to take advantage of caching

# Server package
WORKDIR /usr/src/app/server
COPY server/package*.json ./
RUN npm ci --only=production

# Copy rest of app code

WORKDIR /usr/src/app
COPY . .

# Only needs to run the server, which will pick up ../client/build
WORKDIR /usr/src/app/server
EXPOSE 3000
CMD [ "npm", "start" ]
