version: '3.2'

# In the dev environment, there are client and server images. The server proxies
# through to the client, which is a create-react-app server. The codebases of
# both are mounts on the host filesystem so that you can make changes and have
# them immediately reflected in the running code.
#
# There is also MongoDB instance with a data volume.

services:

  node-dashboard-server:
    build: ../server
    image: dashboard-server
    ports:
      - target: 5000
        published: 3001
    volumes:
      - type: bind
        source: ../server
        target: /usr/src/app
        consistency: delegated
    environment:
      - CLIENT_PROXY_URL=http://node-dashboard-client:3000
      - MONGODB_URL=mongodb://mongo:27017
      - BIRTHDAY
      - GOOGLE_CALENDAR_URL
      - BEEMINDER_USERNAME
      - BEEMINDER_AUTH_TOKEN
      - BEEMINDER_MIT_GOAL
      - TRELLO_KEY
      - TRELLO_TOKEN
      - TRELLO_NEXT_ACTIONS_LIST
      - TRELLO_DONE_LIST
      - TRELLO_MIT_LABEL
    command: ["npm", "run", "startdev"]

  node-dashboard-client:
    build: ../client
    image: dashboard-client
    volumes:
      - type: bind
        source: ../client
        target: /usr/src/app
        consistency: delegated
    command: ["npm", "start"]

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
