version: '3.2'

services:

  node-dashboard:
    build: ../
    image: dashboard
    ports:
      - target: 3000
        published: 3001
    volumes:
      - type: bind
        source: ../
        target: /usr/src/app
        consistency: delegated
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - GOOGLE_CALENDAR_URL
      - BEEMINDER_USERNAME
      - BEEMINDER_AUTH_TOKEN
      - BEEMINDER_MIT_GOAL
      - TRELLO_KEY
      - TRELLO_TOKEN
      - TRELLO_NEXT_ACTIONS_LIST
      - TRELLO_DONE_LIST
      - TRELLO_MIT_LABEL
    command: ["npm", "run", "startdev"]

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_db:/data/db

volumes:
  mongo_db:
