version: '3.2'

services:

  node-dashboard:
    build: ../
    image: dashboard
    ports:
      - target: 3000
        published: 3000
    environment:
      MONGODB_URL: mongodb://mongo:27017
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped

volumes:
  mongo_db:
