version: '3.2'

# In the prod environment, there is a server image, but no client image. The
# client code is built to static files and the server just serves that.
#
# There is also MongoDB instance with a data volume.

services:

  node-dashboard-server:
    build: ../server
    image: dashboard-server
    ports:
      - target: 5000
        published: 3000
    environment:
      - MONGODB_URL=mongodb://mongo:27017
      - BIRTHDAY
      - GOOGLE_CALENDAR_URL
      - BEEMINDER_USERNAME
      - BEEMINDER_AUTH_TOKEN
      - BEEMINDER_MIT_GOAL
      - TRELLO_KEY
      - TRELLO_TOKEN
      - TRELLO_NEXT_ACTIONS_LIST
      - TRELLO_DONE_LIST
      - TRELLO_MIT_LABEL
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped

  mongo:
    image: mongo:3.4
    volumes:
      - mongo_db:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    restart: unless-stopped

volumes:
  mongo_db:
